---
Gemfile:
  optional:
    ':test':
      - gem: 'rexml'
.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_documentation
    - parameter_types
spec/spec_helper.rb:
  spec_overrides:
    - "require 'spec_helper_corosync'"
    - "require 'spec_helper_methods'"
.github/workflows/ci.yml:
  with:
    beaker_hypervisor: 'docker'
